# WEB SCRAPING (RATING PREDICTION):-

# Scrping Rating an reviews:-

In [1]:
#Import necessory libraries
import selenium
import pandas as pd
import time
import  requests
from  bs4 import BeautifulSoup
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
import warnings
warnings.filterwarnings('ignore')

# Scrapping from Flipkart.com:-

In [2]:
# Connecting to the webdriver
driver = webdriver.Chrome("chromedriver.exe")
driver

In [3]:
url = "https://www.flipkart.com/"
driver.get(url)
time.sleep(2)
#clicking on cancel buttopn 
driver.find_element_by_xpath("//div[@class='_2QfC02']/button").click()

In [4]:
srch_items = ['laptops','smart watches', 'Phones','Monitors']

In [5]:
title = []
review_text = []
ratings = []

In [6]:
def scrap():    
        for i in driver.find_elements_by_xpath("//div[@class='t-ZTKy']"):
            review_text.append(i.text)
        for i in driver.find_elements_by_xpath("//p[@class='_2-N8zT']"):
            title.append(i.text)
        for i in driver.find_elements_by_xpath("//p[@class='_2-N8zT']/../div"):
            ratings.append(i.text)
        return

In [7]:
urls=[]

In [8]:
for i in srch_items:
    #Find search bar
    srchBar = driver.find_element_by_xpath("//div[@class='_3OO5Xc']/input")
    srchBar.clear()
    srchBar.send_keys(i)
    #clicking on search button
    driver.find_element_by_xpath("//button[@class='L0Z3Pu']").click()
    time.sleep(3)
    page = []
    for i in driver.find_elements_by_xpath("//nav[@class='yFHi8N']/a"):
        page.append(i.get_attribute('href'))
    for i in page[0:4]:
        driver.get(i)
        time.sleep(3)
        items = driver.find_elements_by_xpath("//a[@class='_1fQZEK']")
        for i in items:
            urls.append(i.get_attribute('href'))

In [9]:
len(urls)

384

In [10]:
for i in urls:
    driver.get(i)
    time.sleep(2)
    for _ in range(2):
        driver.execute_script("window.scrollBy(0,6000)")
        time.sleep(1)
        #clicking on all reviews
    try:
        btn=driver.find_element_by_xpath("//div[@class='_2c2kV-']/following::a")
        lnk = btn.get_attribute('href')
        driver.get(lnk)
        time.sleep(1)
    except NoSuchElementException:
        pass

    scrap()        
    try:
        n_page=driver.find_elements_by_xpath("//nav[@class='yFHi8N']/a")
        np=[]
        for i in n_page:
            np.append(i.get_attribute('href'))
        for i in np[0:18]:
            driver.get(i)
            time.sleep(1)
            scrap()
    except: continue

In [11]:
len(ratings), len(review_text), len(title)

(30681, 30681, 30681)

In [12]:
#creating a dataframe
data = list(zip(title,review_text,ratings))
df2 = pd.DataFrame(data, columns = ["Review_Title","Reiew_Text","Ratings"])
df2

,Review_Title,Reiew_Text,Ratings
0,Worth every penny,Laptop is worth the price. It is fast and smoo...,5
1,Awesome,Value for money just go for it✨,5
2,Great product,good,5
3,Wonderful,It's good product but some times it gets stuck...,4
4,Good quality product,Great Laptop. You can go for it.,4
...,...,...,...
30676,Waste of money!,It is worse screen was damaged,1
30677,Nice,Good,3
30678,Could be way better,Poor quality...,2
30679,Just wow!,Good product,5
30680,Did not meet expectations,Very bad,1

In [13]:
#saving the data into csv file
df2.to_csv("flipkrt1_reviews.csv")

# Scrapping from amazon.in:-

In [2]:
# Connecting to the webdriver
driver = webdriver.Chrome("chromedriver.exe")
driver

In [3]:
url = "https://www.amazon.in/"
driver.get(url)
time.sleep(3)

In [4]:
srch_items = ['headphones','smart watches', 'Professional Cameras','laptops','phones', 'Printers', 'Monitors', 'Home theater', 'Router']

In [5]:
title = []
review_text = []
ratings = []

In [6]:
for i in srch_items:
    srchbar = driver.find_element_by_id("twotabsearchtextbox")
    srchbar.send_keys(i)
    driver.find_element_by_id("nav-search-submit-button").click()  #clicking on search button
    time.sleep(1)
    item_url = []
    for i in driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a"):
        item_url.append(i.get_attribute('href'))
    for i in item_url:
        driver.get(i)
        time.sleep(1)
        for _ in range(2):
            driver.execute_script("window.scrollBy(0,6000)")
            time.sleep(1)
        #click on see all reviews
        try:
            driver.find_element_by_xpath("//a[@class='a-link-emphasis a-text-bold']").click()
        except:
            pass
        
        url_ = []
        try:
            two_str = driver.find_element_by_xpath("//table[@id='histogramTable']/tbody/tr[4]/td[2]/a")
            url_.append(two_str.get_attribute('href'))
        except: pass
        try:
            three_str = driver.find_element_by_xpath("//table[@id='histogramTable']/tbody/tr[3]/td[2]/a")
            url_.append(three_str.get_attribute('href'))
        except: pass
        try:
            one_str = driver.find_element_by_xpath("//table[@id='histogramTable']/tbody/tr[5]/td[2]/a")
            url_.append(one_str.get_attribute('href'))
        except: pass
        try:
            fiv_str = driver.find_element_by_xpath("//table[@id='histogramTable']/tbody/tr[1]/td[2]/a")
            url_.append(fiv_str.get_attribute('href'))
        except: pass
        try:
            four_str = driver.find_element_by_xpath("//table[@id='histogramTable']/tbody/tr[2]/td[2]/a")
            url_.append(four_str.get_attribute('href'))
        except: pass
        
        for i in url_:
            driver.get(i)
            time.sleep(1)
            for i in range(10):
                ids = driver.find_elements_by_xpath("//div[@class='a-section a-spacing-none review-views celwidget']/div")
                comment_ids = []
                for i in ids:
                    comment_ids.append(i.get_attribute('id'))

                for x in comment_ids:
                    #Extract user ids from each user on a page
                    try:
                        review_title = driver.find_element_by_xpath('//*[@id="' + x +'"]/div/div/div[2]/a[2]/span[1]')
                        title.append(review_title.get_attribute("innerHTML"))
                    except NoSuchElementException:
                        title.append('')

                    try:
                        rating = driver.find_element_by_xpath('//*[@id="' + x +'"]/div/div/div[2]/a[1]/i/span[1]')
                        ratings.append(rating.get_attribute("innerHTML"))
                    except NoSuchElementException:
                        ratings.append('')

                    try:
                        text = driver.find_element_by_xpath('//*[@id="' + x +'"]/div/div/div[4]/span/span')
                        review_text.append(text.get_attribute("innerHTML"))
                    except NoSuchElementException:
                        review_text.append('')
                try:
                    driver.find_element_by_xpath("//ul[@class='a-pagination']/li[2]/a").click()
                    time.sleep(3)
                except : break

In [7]:
len(ratings), len(title), len(review_text)

(83810, 83810, 83810)

In [8]:
#creating a dataframe
data = list(zip(title,review_text,ratings))
df = pd.DataFrame(data, columns = ["Review_title","Reiew_text","Ratings"])
df

,Review_title,Reiew_text,Ratings
0,Think twice before going for it,\n &nbsp;Pros<br>-----<br>- Very light weight...,2.0 out of 5 stars
1,Overpriced,\n Overpriced for this mediocre product with ...,2.0 out of 5 stars
2,Build quality is not as good as shown in the Ad,\n Did not meet expectations:<br>Takes signif...,3.0 out of 5 stars
3,Speed and Visuals makes this a power machine!,\n The speakers and sound quality are patheti...,3.0 out of 5 stars
4,Overpriced and unreliable,\n For just i5 11th gen this laptop is way ov...,3.0 out of 5 stars
...,...,...,...
83805,Vfm. Range of Archer c6 or A6 without mu-mimo,\n Same wifi signal range as c6 or the new A6...,4.0 out of 5 stars
83806,USB port is not supported for printer,\n USB port is not supporting printer so I a...,4.0 out of 5 stars
83807,A best buy for that price range,"\n Like : Speed , look and also better range ...",4.0 out of 5 stars
83808,Value For Money,\n Got it for 2K. Wifi signal in 2.4 Ghz is v...,4.0 out of 5 stars
83809,,,

In [9]:
#saving the data into csv file
df.to_csv("amazon1_reviews.csv")

In [2]:
#lets load the flipkart reviews file
flpkrt = pd.read_csv("flipkrt1_reviews.csv")
flpkrt

,Unnamed: 0,Review_Title,Reiew_Text,Ratings
0,0,Worth every penny,Laptop is worth the price. It is fast and smoo...,5
1,1,Awesome,Value for money just go for it✨,5
2,2,Great product,good,5
3,3,Wonderful,It's good product but some times it gets stuck...,4
4,4,Good quality product,Great Laptop. You can go for it.,4
...,...,...,...,...
30676,30676,Waste of money!,It is worse screen was damaged,1
30677,30677,Nice,Good,3
30678,30678,Could be way better,Poor quality...,2
30679,30679,Just wow!,Good product,5
30680,30680,Did not meet expectations,Very bad,1

In [3]:
#lets load the amazon reviews file
df1 = pd.read_csv("amazon1_reviews.csv")
df1

,Unnamed: 0,Review_title,Reiew_text,Ratings
0,0,Think twice before going for it,\n &nbsp;Pros<br>-----<br>- Very light weight...,2.0 out of 5 stars
1,1,Overpriced,\n Overpriced for this mediocre product with ...,2.0 out of 5 stars
2,2,Build quality is not as good as shown in the Ad,\n Did not meet expectations:<br>Takes signif...,3.0 out of 5 stars
3,3,Speed and Visuals makes this a power machine!,\n The speakers and sound quality are patheti...,3.0 out of 5 stars
4,4,Overpriced and unreliable,\n For just i5 11th gen this laptop is way ov...,3.0 out of 5 stars
...,...,...,...,...
83805,83805,Vfm. Range of Archer c6 or A6 without mu-mimo,\n Same wifi signal range as c6 or the new A6...,4.0 out of 5 stars
83806,83806,USB port is not supported for printer,\n USB port is not supporting printer so I a...,4.0 out of 5 stars
83807,83807,A best buy for that price range,"\n Like : Speed , look and also better range ...",4.0 out of 5 stars
83808,83808,Value For Money,\n Got it for 2K. Wifi signal in 2.4 Ghz is v...,4.0 out of 5 stars
83809,83809,NaN,NaN,NaN

**Since to concat the column names should be same in both the files so let me change the column names in both the files as if they are same.**

In [4]:
# Changing the column name in amazon file similar to flipkart file
df1.rename(columns = {'Review_title':'Review_Title'}, inplace = True)

In [5]:
# Changing the column name in amazon file similar to flipkart file
df1.rename(columns = {'Reiew_text':'Review_Text'}, inplace = True)

In [6]:
# Changing the column name in flipkart file
flpkrt.rename(columns = {'Reiew_Text':'Review_Text'}, inplace = True)

**Since unnamed :0 is the index column lets drop it in both the files.**

In [7]:
# Dropping Unnamed: 0 in flpkrt file
flpkrt.drop(columns = 'Unnamed: 0', inplace=True)

In [8]:
# Dropping Unnamed: 0 in amazon file
df1.drop(columns = 'Unnamed: 0', inplace=True)

Now the files are ready to concat.

In [9]:
#Concating both the files
RP = pd.concat([df1, flpkrt],ignore_index=True)
RP

,Review_Title,Review_Text,Ratings
0,Think twice before going for it,\n &nbsp;Pros<br>-----<br>- Very light weight...,2.0 out of 5 stars
1,Overpriced,\n Overpriced for this mediocre product with ...,2.0 out of 5 stars
2,Build quality is not as good as shown in the Ad,\n Did not meet expectations:<br>Takes signif...,3.0 out of 5 stars
3,Speed and Visuals makes this a power machine!,\n The speakers and sound quality are patheti...,3.0 out of 5 stars
4,Overpriced and unreliable,\n For just i5 11th gen this laptop is way ov...,3.0 out of 5 stars
...,...,...,...
114486,Waste of money!,It is worse screen was damaged,1
114487,Nice,Good,3
114488,Could be way better,Poor quality...,2
114489,Just wow!,Good product,5
114490,Did not meet expectations,Very bad,1

Now the data is ready let's save it in csv format.

In [10]:
#saving the data into csv file
RP.to_csv("R_P.csv")